name: Docker Image Push

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    permissions:
        contents: read
        packages: write
    runs-on: ubuntu-latest
    steps:
    - id: lower-repo
      name: Lowercase Repository Name
      run: |
        echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      env:
        BUILDX_NO_DEFAULT_ATTESTATIONS: 1
      with:
        platforms: linux/amd64,linux/arm64
        install: true
    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker Image
      working-directory: ${{ github.workspace }}/GameApi
      run: docker build . --tag ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest --push
    - name: SSH to VM and Update Docker
      uses: appleboy/ssh-action@master
      with:
          host: ${{ vars.VM_DOMAIN_API }}
          username: ubuntu
          key: ${{ secrets.VM_SSHKEY_API }}
          script: sudo docker compose ps -a; sudo docker compose pull; sudo docker compose up -d; cat compose.yaml; sudo docker compose ps -a
