name: Docker Image Push

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    permissions:
        contents: read
        packages: write
    runs-on: ubuntu-latest
    steps:
    - id: lower-repo
      name: Lowercase Repository Name
      run: |
        echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
    - name: Build Docker Image
      working-directory: ${{ github.workspace }}/GameApi
      run: docker build . --tag ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker Image
      run: docker push ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
  ssh_droplet_update:
    name: SSH to VM and Update Docker
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VM_DOMAIN_API }}
          username: ubuntu
          key: ${{ secrets.VM_SSHKEY_API }}
          script: |
            la -la
            pwd
