name: Docker Image Push

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    permissions:
        contents: read
        packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      working-directory: ${{ github.workspace }}/GameApi
      run: docker build . --tag ghcr.io/campusgeoapi:latest
    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker Image
      run: docker push ghcr.io/campusgeoapi:latest
  # ssh_droplet_update:
    # needs: build_and_push_image
    # uses: Unicycle-Unicorn/CICD/.github/workflows/droplet-ssh-pull-up.yml@main
    # with:
      # services: 'cam'
    # secrets: inherit
